In [15]:
import pandas as pd
import numpy as np
import os

In [16]:
np.__version__


'1.20.1'

In [17]:
pd.__version__

'1.2.4'

In [19]:
df=pd.read_csv('C:\\Users\\Tapas.Tiwari\\Desktop\\Python Notebooks\\ml-zoomcamp\\carpricedata.csv')

In [20]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [29]:
bmw = df[df['Make']== "BMW"]
avgprice = bmw['MSRP'].mean()
avgprice

61546.76347305389

In [31]:
after2015 = df[df['Year']>=2015]
after2015.head()

Make       Model  Year                Engine Fuel Type  Engine HP  \
32  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
33  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
34  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
41   BMW    2 Series  2016     premium unleaded (required)      240.0   
42   BMW    2 Series  2016     premium unleaded (required)      240.0   

    Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
32               4.0            MANUAL  rear wheel drive              2.0   
33               4.0            MANUAL  rear wheel drive              2.0   
34               4.0            MANUAL  rear wheel drive              2.0   
41               4.0         AUTOMATIC  rear wheel drive              2.0   
42               4.0         AUTOMATIC  rear wheel drive              2.0   

       Market Category Vehicle Size Vehicle Style  highway MPG  city mpg  \
32         Performance      Compact   Convertible           35        26   
33         Performance      Compact   Convertible           35        26   
34         Performance      Compact   Convertible           35        26   
41  Luxury,Performance      Compact         Coupe           35        23   
42              Luxury      Compact   Convertible           34        23   

    Popularity   MSRP  
32         819  27495  
33         819  24995  
34         819  28195  
41        3916  32850  
42        3916  38650

In [32]:
after2015.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        0
Engine HP              51
Engine Cylinders        8
Transmission Type       0
Driven_Wheels           0
Number of Doors         5
Market Category      1324
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [34]:
after2015['Engine HP'].mean()

272.98771870794076

In [38]:
values = {'Engine HP': 272.98}
after2015.fillna(value = values)

Make       Model  Year                Engine Fuel Type  Engine HP  \
32     FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
33     FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
34     FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
41      BMW    2 Series  2016     premium unleaded (required)      240.0   
42      BMW    2 Series  2016     premium unleaded (required)      240.0   
...     ...         ...   ...                             ...        ...   
11898   BMW          Z4  2015     premium unleaded (required)      300.0   
11899   BMW          Z4  2015     premium unleaded (required)      335.0   
11900   BMW          Z4  2016     premium unleaded (required)      300.0   
11901   BMW          Z4  2016     premium unleaded (required)      240.0   
11902   BMW          Z4  2016     premium unleaded (required)      335.0   

       Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
32                  4.0            MANUAL  rear wheel drive              2.0   
33                  4.0            MANUAL  rear wheel drive              2.0   
34                  4.0            MANUAL  rear wheel drive              2.0   
41                  4.0         AUTOMATIC  rear wheel drive              2.0   
42                  4.0         AUTOMATIC  rear wheel drive              2.0   
...                 ...               ...               ...              ...   
11898               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   
11899               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   
11900               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   
11901               4.0            MANUAL  rear wheel drive              2.0   
11902               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   

               Market Category Vehicle Size Vehicle Style  highway MPG  \
32                 Performance      Compact   Convertible           35   
33                 Performance      Compact   Convertible           35   
34                 Performance      Compact   Convertible           35   
41          Luxury,Performance      Compact         Coupe           35   
42                      Luxury      Compact   Convertible           34   
...                        ...          ...           ...          ...   
11898  Luxury,High-Performance      Compact   Convertible           24   
11899  Luxury,High-Performance      Compact   Convertible           24   
11900  Luxury,High-Performance      Compact   Convertible           24   
11901       Luxury,Performance      Compact   Convertible           34   
11902  Luxury,High-Performance      Compact   Convertible           24   

       city mpg  Popularity   MSRP  
32           26         819  27495  
33           26         819  24995  
34           26         819  28195  
41           23        3916  32850  
42           23        3916  38650  
...         ...         ...    ...  
11898        17        3916  56950  
11899        17        3916  65800  
11900        17        3916  57500  
11901        22        3916  49700  
11902        17        3916  66350  

[5995 rows x 16 columns]

In [39]:
after2015['Engine HP'].mean()

272.98771870794076

In [44]:
rollsroyce = df[df['Make']== "Rolls-Royce"]
rollsroyce.head()

Make            Model  Year             Engine Fuel Type  \
2921  Rolls-Royce         Corniche  2001  premium unleaded (required)   
3505  Rolls-Royce             Dawn  2016  premium unleaded (required)   
5275  Rolls-Royce  Ghost Series II  2015  premium unleaded (required)   
5276  Rolls-Royce  Ghost Series II  2015  premium unleaded (required)   
5277  Rolls-Royce  Ghost Series II  2016  premium unleaded (required)   

      Engine HP  Engine Cylinders Transmission Type     Driven_Wheels  \
2921      325.0               8.0         AUTOMATIC  rear wheel drive   
3505      563.0              12.0         AUTOMATIC  rear wheel drive   
5275      563.0              12.0         AUTOMATIC  rear wheel drive   
5276      563.0              12.0         AUTOMATIC  rear wheel drive   
5277      563.0              12.0         AUTOMATIC  rear wheel drive   

      Number of Doors                 Market Category Vehicle Size  \
2921              2.0                   Exotic,Luxury        Large   
3505              2.0  Exotic,Luxury,High-Performance        Large   
5275              4.0       Exotic,Luxury,Performance        Large   
5276              4.0       Exotic,Luxury,Performance        Large   
5277              4.0       Exotic,Luxury,Performance        Large   

     Vehicle Style  highway MPG  city mpg  Popularity    MSRP  
2921   Convertible           15        10          86  359990  
3505   Convertible           19        12          86  335000  
5275         Sedan           21        13          86  286750  
5276         Sedan           21        13          86  319400  
5277         Sedan           21        13          86  295850

In [114]:
rollsroyce = rollsroyce[['Engine HP', 'Engine Cylinders', 'highway MPG']]

In [118]:
rollsroyce=rollsroyce.drop_duplicates()

In [119]:
X = rollsroyce.values

In [120]:
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [121]:
XT =X.T
XTX = X.T.dot(X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [122]:
XTXInv = np.linalg.inv(XTX)
XTXInv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [123]:
XTXInv.sum()

0.032212320677486195

In [124]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

In [125]:
w=XTXInv.dot(X.T).dot(y)

In [126]:
w

array([ 0.19989598, 31.02612262, 31.65378877])